name: build-and-deploy
on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.62.2'
          extended: true

      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.TOKEN }} 
          external_repository: vvcc-yu/vvcchugo.github.io # Pages 远程仓库 
          publish_dir: "./public"
          publish_branch: main 
          commit_message: ${{ github.event.head_commit.message }}
